### ISSUE TITLE
Align with .net 8 TimeProvider

### ISSUE THREAD

**Issue by egil** [egil/TimeProviderExtensions#1]
https://github.com/dotnet/runtime/commit/5d88ff404de77d78e07ad3de7fa2af270332da22

https://github.com/dotnet/runtime/issues/36617

**Comment by agehrke** [comment]
I was thinking about pinging you when I saw David Fowler’s thread on Twitter this morning. But then concluded you either already knew about the feature or would see the thread anyway 🙂

**Comment by egil** [comment]
@agehrke do you know if there is a plan to do a fake/test implementation of `TimeProvider` in the framework? If yes, then I can sunset my efforts 🙂

**Comment by agehrke** [comment]
Yeah I was thinking the same thing. The API proposal doesn’t seem to include any fake or “manual” TimeProviders. But I hope they will create an internal one that they share between components, eg like ValueStopwatch or NonCapturingTimer. Then I will be copy/pasting that 😀
