### ISSUE TITLE
Strong-named assemblies support

### ISSUE THREAD

**Issue by quinmars** [egil/TimeProviderExtensions#3]
We plan to use this library for our unit tests, which, however, have strong named assemblies. Are there any plans to make the assembly strong-named? At the moment we use the `Microsoft.Extensions.TimeProvider.Testing` nuget package, which generates warning for .NET Versions below 8.

**Comment by egil** [comment]
That should not be a problem to add. I'll put it on my todo list.

If you want to send in a PR that's also ok.

**Comment by egil** [comment]
Thanks for the help with this @quinmars.

Btw. Was wondering what warnings you are seeing with Microsofts FakeTimeProvider?

**Comment by quinmars** [comment]
> Btw. Was wondering what warnings you are seeing with Microsofts FakeTimeProvider?

I get the following warning. I guess they will remove it, once .NET 8 is released. But since I find the behavior of your `Advance` method more useful, I thought, it is a good moment to switch the testing library.

> Microsoft.Extensions.TimeProvider.Testing 8.0.0-preview.6.23360.2 doesn't support net6.0 and has not been tested with it. Consider upgrading your TargetFramework to net8.0 or later. You may also set \<SuppressTfmSupportBuildWarnings\>true\</SuppressTfmSupportBuildWarnings\> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.

**Comment by egil** [comment]
Yeah, I helped build FakeTimeProvider and there was an extensive debate around how Advance should work, but the dotnet team decided to go with what they did so I decided to keep my version around as well.

**Comment by quinmars** [comment]
I have seen the discussions. Good work!
